function ipcScopeGet(k) {
    switch (k) {
        case 'BrowserWindow': return BrowserWindow;
        case 'CaptchaSolverError': return CaptchaSolverError;
        case 'ExternalProxyPort': return ExternalProxyPort;
        case 'ProxyChain': return ProxyChain;
        case '_analyzeCaptchaScript': return _analyzeCaptchaScript;
        case '_analyzeEndpointsScript': return _analyzeEndpointsScript;
        case '_analyzeFormsScript': return _analyzeFormsScript;
        case '_analyzeMetaScript': return _analyzeMetaScript;
        case '_broadcastCompareUpdated': return _broadcastCompareUpdated;
        case '_broadcastLogEntryToViewers': return _broadcastLogEntryToViewers;
        case '_comparePayload': return _comparePayload;
        case '_confidence': return _confidence;
        case '_cupnetRoot': return _cupnetRoot;
        case '_lastPointerByTabId': return _lastPointerByTabId;
        case '_pairScore': return _pairScore;
        case '_reqWithCompareOptions': return _reqWithCompareOptions;
        case '_requestsForSessionAsc': return _requestsForSessionAsc;
        case '_serializeCompareRowRequest': return _serializeCompareRowRequest;
        case '_wcIdToTabId': return _wcIdToTabId;
        case 'actProxy': return actProxy;
        case 'activeExtPorts': return activeExtPorts;
        case 'activeFingerprint': return activeFingerprint;
        case 'app': return app;
        case 'applyBypassDomains': return applyBypassDomains;
        case 'applyEffectiveTrafficMode': return applyEffectiveTrafficMode;
        case 'applyFingerprintToAllTabs': return applyFingerprintToAllTabs;
        case 'applyTrafficFilters': return applyTrafficFilters;
        case 'broadcastInterceptRuleMatched': return broadcastInterceptRuleMatched;
        case 'broadcastTlsProfileChanged': return broadcastTlsProfileChanged;
        case 'buildMenu': return buildMenu;
        case 'bundleUtils': return bundleUtils;
        case 'checkCurrentIpGeo': return checkCurrentIpGeo;
        case 'clipboard': return clipboard;
        case 'comparePair': return comparePair;
        case 'compareResult': return compareResult;
        case 'connectProxyWithFailover': return connectProxyWithFailover;
        case 'connectedProfileId': return connectedProfileId;
        case 'connectedProfileName': return connectedProfileName;
        case 'connectedResolvedVars': return connectedResolvedVars;
        case 'consoleCaptureApi': return consoleCaptureApi;
        case 'consoleViewerWindow': return consoleViewerWindow;
        case 'createCompareViewerWindow': return createCompareViewerWindow;
        case 'createConsoleViewerWindow': return createConsoleViewerWindow;
        case 'createCookieManagerWindow': return createCookieManagerWindow;
        case 'createDnsManagerWindow': return createDnsManagerWindow;
        case 'createIvacScoutWindow': return createIvacScoutWindow;
        case 'createLogViewerWindow': return createLogViewerWindow;
        case 'createLoggingModalWindow': return createLoggingModalWindow;
        case 'createPageAnalyzerWindow': return createPageAnalyzerWindow;
        case 'createProxyManagerWindow': return createProxyManagerWindow;
        case 'createRequestEditorWindow': return createRequestEditorWindow;
        case 'createRulesWindow': return createRulesWindow;
        case 'createTraceViewerWindow': return createTraceViewerWindow;
        case 'currentSessionId': return currentSessionId;
        case 'db': return db;
        case 'dialog': return dialog;
        case 'diffUtils': return diffUtils;
        case 'extPortErrors': return extPortErrors;
        case 'extPortsStore': return extPortsStore;
        case 'fs': return fs;
        case 'generatePassword': return generatePassword;
        case 'getCapmonsterSettings': return getCapmonsterSettings;
        case 'getCurrentTrafficMode': return getCurrentTrafficMode;
        case 'getInternalPageUrl': return getInternalPageUrl;
        case 'getIvacScoutContext': return getIvacScoutContext;
        case 'getLiveLogViewerWindow': return getLiveLogViewerWindow;
        case 'getLocalIp': return getLocalIp;
        case 'getNewTabUrl': return getNewTabUrl;
        case 'getTrackingSettings': return getTrackingSettings;
        case 'hadLoggingBeenStopped': return hadLoggingBeenStopped;
        case 'harExporter': return harExporter;
        case 'interceptor': return interceptor;
        case 'ipcMain': return ipcMain;
        case 'isLoggingEnabled': return isLoggingEnabled;
        case 'isValidDnsHost': return isValidDnsHost;
        case 'isValidIpv4': return isValidIpv4;
        case 'lastMouseMoveTime': return lastMouseMoveTime;
        case 'loadJsonDiffModules': return loadJsonDiffModules;
        case 'loadSettings': return loadSettings;
        case 'logEntryCount': return logEntryCount;
        case 'logViewerInitSessions': return logViewerInitSessions;
        case 'logViewerWindow': return logViewerWindow;
        case 'logViewerWindows': return logViewerWindows;
        case 'mainWindow': return mainWindow;
        case 'maybeLogStartupMetrics': return maybeLogStartupMetrics;
        case 'mitmProxy': return mitmProxy;
        case 'mitmReady': return mitmReady;
        case 'nativeImage': return nativeImage;
        case 'netFetchWithTimeout': return netFetchWithTimeout;
        case 'networkPolicy': return networkPolicy;
        case 'normalizeCapmonsterSettings': return normalizeCapmonsterSettings;
        case 'normalizeTrackingSettings': return normalizeTrackingSettings;
        case 'normalizeTrafficMode': return normalizeTrafficMode;
        case 'notifyCookieManagerTabs': return notifyCookieManagerTabs;
        case 'notifyProxyProfilesList': return notifyProxyProfilesList;
        case 'notifyProxyStatus': return notifyProxyStatus;
        case 'parseFallbackProxyList': return parseFallbackProxyList;
        case 'parseProxyTemplate': return parseProxyTemplate;
        case 'path': return path;
        case 'persistentAnonymizedProxyUrl': return persistentAnonymizedProxyUrl;
        case 'proxyResilience': return proxyResilience;
        case 'quickChangeProxy': return quickChangeProxy;
        case 'reattachInterceptorToAllTabs': return reattachInterceptorToAllTabs;
        case 'requestScreenshot': return requestScreenshot;
        case 'resetFingerprintOnWebContents': return resetFingerprintOnWebContents;
        case 'resolveNavigationUrl': return resolveNavigationUrl;
        case 'rulesWindow': return rulesWindow;
        case 'runIvacScoutProcess': return runIvacScoutProcess;
        case 'safeCatch': return safeCatch;
        case 'safeStorage': return safeStorage;
        case 'saveSettings': return saveSettings;
        case 'sendLogStatus': return sendLogStatus;
        case 'session': return session;
        case 'settingsStore': return settingsStore;
        case 'setupNetworkLogging': return setupNetworkLogging;
        case 'shell': return shell;
        case 'solveTurnstileWithCapMonster': return solveTurnstileWithCapMonster;
        case 'stabilityMetrics': return stabilityMetrics;
        case 'startupMetrics': return startupMetrics;
        case 'stopIvacScoutProcess': return stopIvacScoutProcess;
        case 'syncDnsOverridesToMitm': return syncDnsOverridesToMitm;
        case 'sysLog': return sysLog;
        case 'tabManager': return tabManager;
        case 'testProxy': return testProxy;
        case 'traceWindows': return traceWindows;
        case 'uiPrefsStore': return uiPrefsStore;
        case 'withTimeout': return withTimeout;
        default: return undefined;
    }
}
function ipcScopeSet(k, v) {
    switch (k) {
        case 'actProxy': actProxy = v; return;
        case 'activeFingerprint': activeFingerprint = v; return;
        case 'compareResult': compareResult = v; return;
        case 'connectedProfileId': connectedProfileId = v; return;
        case 'connectedProfileName': connectedProfileName = v; return;
        case 'connectedResolvedVars': connectedResolvedVars = v; return;
        case 'currentSessionId': currentSessionId = v; return;
        case 'hadLoggingBeenStopped': hadLoggingBeenStopped = v; return;
        case 'isLoggingEnabled': isLoggingEnabled = v; return;
        case 'lastMouseMoveTime': lastMouseMoveTime = v; return;
        case 'logEntryCount': logEntryCount = v; return;
        case 'persistentAnonymizedProxyUrl': persistentAnonymizedProxyUrl = v; return;
        default: throw new Error("IPC read-only: " + k);
    }
}
